// Generated by Dagger (https://dagger.dev).
package com.example.itoken.features.assetlibrary.domain.usecase;

import com.example.itoken.features.assetlibrary.domain.repository.AssetRepository;
import com.example.itoken.utils.DispatcherProvider;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetAssetsUseCase_Factory implements Factory<GetAssetsUseCase> {
  private final Provider<AssetRepository> repositoryProvider;

  private final Provider<DispatcherProvider> scopeProvider;

  public GetAssetsUseCase_Factory(Provider<AssetRepository> repositoryProvider,
      Provider<DispatcherProvider> scopeProvider) {
    this.repositoryProvider = repositoryProvider;
    this.scopeProvider = scopeProvider;
  }

  @Override
  public GetAssetsUseCase get() {
    return newInstance(repositoryProvider.get(), scopeProvider.get());
  }

  public static GetAssetsUseCase_Factory create(Provider<AssetRepository> repositoryProvider,
      Provider<DispatcherProvider> scopeProvider) {
    return new GetAssetsUseCase_Factory(repositoryProvider, scopeProvider);
  }

  public static GetAssetsUseCase newInstance(AssetRepository repository, DispatcherProvider scope) {
    return new GetAssetsUseCase(repository, scope);
  }
}
